# This defines our new 'Cluster'
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: clusters.cnp.accenture.com
spec:
  connectionSecretKeys:
  - kubeconfig
  publish: true
  crdSpecTemplate:
    group: cnp.accenture.com
    version: v1alpha1
    names:
      kind: Cluster
      listKind: ClusterList
      plural: clusters
      singular: cluster
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              nodes:
                type: integer
                description: Number of nodes in the cluster
